### ISSUE TITLE
Oj byczki

### ISSUE THREAD

**Issue by CichyJohnny** [pwlsp/put-invaders#1]
Pliki nagłówkowe w cpp mają rozszerzenie .hpp, nie .h

Pozdrawiam.

**Comment by pwlsp** [comment]
xD

**Comment by pwlsp** [comment]
Jak sprawdziłem w necie to mi się wyświetliło, że .hpp jest przereklamowane.

**Comment by CichyJohnny** [comment]
Może i tak, lul mogę edytować Twoją wiadomość xd

Zamykam wątek.
![Bez tytułu](https://github.com/user-attachments/assets/45a31ddc-4b51-4a04-82b6-cab518703cce)

**Comment by pwlsp** [comment]
Hola, to ja tu jestem od zamykania wątków.

Zamykam wątek.

**Comment by CichyJohnny** [comment]
Aha,
dobrze że dostaje maila z każdą twoją ingerencją w ten wątek >:(
